config/routes.rb
Rails.application.routes.draw do
  get "/m/:id(.:format)", controller: :home, action: :show, :constraints => {:id => /\d+/}
  get "/h/:hash(.:format)", controller: :home, action: :show_by_hash

  resources :images

  resources :strokes

  resources :theta

  resources :hmock_websocketview
  resources :glue, only: [:show]

  get '/test' => 'theta#test'
end

app/models/theta.rb
class Theta < ActiveRecord::Base
  has_many :strokes
end

app/controllers/theta_controller.rb
class ThetaController < ApplicationController
  before_action :set_theta, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :create

  def test
  end

  # GET /theta
  # GET /theta.json
  def index
    @theta = Theta.all
  end

  # GET /theta/1
  # GET /theta/1.json
  def show
  end

  # GET /theta/new
  def new
    @theta = Theta.new
  end

  # GET /theta/1/edit
  def edit
  end

  # POST /theta
  # POST /theta.json
  def create
    request_image = params[:image]
    url_hash = SecureRandom.urlsafe_base64(6)
    name = url_hash + "-" + request_image.original_filename.downcase

    File.open("#{Rails.root}/public/theta/#{name}", 'wb') do |f|
      f.write(request_image.read)
    end

    theta = Theta.create!(url_hash: url_hash, image_url: name)
    render json: {url: "http://www.rakugaki.tk/h/#{theta.url_hash}"}, status: 201
  end

  # PATCH/PUT /theta/1
  # PATCH/PUT /theta/1.json
  def update
    respond_to do |format|
      if @theta.update(theta_params)
        format.html { redirect_to @theta, notice: 'Theta was successfully updated.' }
        format.json { render :show, status: :ok, location: @theta }
      else
        format.html { render :edit }
        format.json { render json: @theta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theta/1
  # DELETE /theta/1.json
  def destroy
    @theta.destroy
    respond_to do |format|
      format.html { redirect_to theta_url, notice: 'Theta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theta
      @theta = Theta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theta_params
#      params.require(:image).permit(:url_hash, :image_url)
      params.permit(:image, :url_hash, :image_url)
    end
end

app/helpers/theta_helper.rb
module ThetaHelper
end

app/views/theta/_form.html.erb
<%= form_for(@thetum) do |f| %>
  <% if @thetum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thetum.errors.count, "error") %> prohibited this thetum from being saved:</h2>

      <ul>
      <% @thetum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_hash %><br>
    <%= f.text_field :url_hash %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theta/edit.html.erb
<h1>Editing thetum</h1>

<%= render 'form' %>

<%= link_to 'Show', @thetum %> |
<%= link_to 'Back', theta_path %>

app/views/theta/index.html.erb
<h1>Listing theta</h1>

<table>
  <thead>
    <tr>
      <th>Url hash</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theta.each do |thetum| %>
      <tr>
        <td><%= thetum.url_hash %></td>
        <td><%= thetum.image_url %></td>
        <td><%= link_to 'Show', thetum %></td>
        <td><%= link_to 'Edit', edit_thetum_path(thetum) %></td>
        <td><%= link_to 'Destroy', thetum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thetum', new_thetum_path %>

app/views/theta/new.html.erb
<h1>New thetum</h1>

<%= render 'form' %>

<%= link_to 'Back', theta_path %>

app/views/theta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url hash:</strong>
  <%= @thetum.url_hash %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @thetum.image_url %>
</p>

<%= link_to 'Edit', edit_thetum_path(@thetum) %> |
<%= link_to 'Back', theta_path %>

app/views/theta/test.html.erb
<%= stylesheet_link_tag "theta" %>
<%= javascript_include_tag "OrbitControls" %>
<%= javascript_include_tag "Detector" %>
<%= javascript_include_tag "yanoo.client" %>
<%= javascript_include_tag "drawers" %>
<%= javascript_include_tag "theta" %>

<div id="sphere" data-image="<%= asset_path "1st_meeting.jpg" %>" data-width="800" data-height="500" data-id="2">
	<div class="control-buttons">
		<div class="control-button inline" id="toggle-edit-button">Edit</div>
		<div id="edit-controls" class="hidden">
			<div class="control-button mode-button" data-drawer="RedParticleDrawer">◉</div>
			<div class="control-button mode-button" data-drawer="GreenParticleDrawer">▲</div>
			<div class="control-button mode-button" data-drawer="RainbowParticleDrawer">☀</div>
			<div class="control-button mode-button" data-drawer="DelayedDrawer">☃</div>
			<!-- <div class="control-button mode-button" data-drawer="ImageDrawer">ピヨ</div> -->

			<div id="stroke-size-select">
				<input id="stroke-size-3" name="stroke-size" type="radio" value="3">
				<label for="stroke-size-3" style="cursor:pointer">大</label>
				<input id="stroke-size-2" name="stroke-size" type="radio" value="2" checked="checked">
				<label for="stroke-size-2" style="cursor:pointer">中</label>
				<input id="stroke-size-1" name="stroke-size" type="radio" value="1">
				<label for="stroke-size-1" style="cursor:pointer">小</label>
			</div>

		</div>
	</div>
</div>