config/routes.rb
Rails.application.routes.draw do
  get "/m/:id(.:format)", controller: :home, action: :show, :constraints => {:id => /\d+/}
  get "/h/:hash(.:format)", controller: :home, action: :show_by_hash

  resources :images

  resources :strokes

  resources :theta

  resources :hmock_websocketview
  resources :glue, only: [:show]

  get '/test' => 'theta#test'
end

app/models/stroke.rb
class Stroke < ActiveRecord::Base
  belongs_to :theta

  def to_hash
    {
      theta_id: theta_id,
      type_id: type_id,
      shape_id: shape_id,
      pos: JSON.parse(pos),
    }
  end
end

app/controllers/strokes_controller.rb
class StrokesController < ApplicationController
  before_action :set_stroke, only: [:show, :edit, :update, :destroy]

  # GET /strokes
  # GET /strokes.json
  def index
    @strokes = Stroke.all
  end

  # GET /strokes/1
  # GET /strokes/1.json
  def show
  end

  # GET /strokes/new
  def new
    @stroke = Stroke.new
  end

  # GET /strokes/1/edit
  def edit
  end

  # POST /strokes
  # POST /strokes.json
  def create
    @stroke = Stroke.new(stroke_params)

    respond_to do |format|
      if @stroke.save
        format.html { redirect_to @stroke, notice: 'Stroke was successfully created.' }
        format.json { render :show, status: :created, location: @stroke }
      else
        format.html { render :new }
        format.json { render json: @stroke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strokes/1
  # PATCH/PUT /strokes/1.json
  def update
    respond_to do |format|
      if @stroke.update(stroke_params)
        format.html { redirect_to @stroke, notice: 'Stroke was successfully updated.' }
        format.json { render :show, status: :ok, location: @stroke }
      else
        format.html { render :edit }
        format.json { render json: @stroke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strokes/1
  # DELETE /strokes/1.json
  def destroy
    @stroke.destroy
    respond_to do |format|
      format.html { redirect_to strokes_url, notice: 'Stroke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stroke
      @stroke = Stroke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stroke_params
      params.require(:stroke).permit(:theta_id, :type_id, :shape_id, :pos)
    end
end

app/helpers/strokes_helper.rb
module StrokesHelper
end

app/views/strokes/_form.html.erb
<%= form_for(@stroke) do |f| %>
  <% if @stroke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stroke.errors.count, "error") %> prohibited this stroke from being saved:</h2>

      <ul>
      <% @stroke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :theta_id %><br>
    <%= f.text_field :theta_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :shape_id %><br>
    <%= f.number_field :shape_id %>
  </div>
  <div class="field">
    <%= f.label :pos %><br>
    <%= f.text_area :pos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strokes/edit.html.erb
<h1>Editing stroke</h1>

<%= render 'form' %>

<%= link_to 'Show', @stroke %> |
<%= link_to 'Back', strokes_path %>

app/views/strokes/index.html.erb
<h1>Listing strokes</h1>

<table>
  <thead>
    <tr>
      <th>Theta</th>
      <th>Type</th>
      <th>Shape</th>
      <th>Pos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strokes.each do |stroke| %>
      <tr>
        <td><%= stroke.theta %></td>
        <td><%= stroke.type_id %></td>
        <td><%= stroke.shape_id %></td>
        <td><%= stroke.pos %></td>
        <td><%= link_to 'Show', stroke %></td>
        <td><%= link_to 'Edit', edit_stroke_path(stroke) %></td>
        <td><%= link_to 'Destroy', stroke, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stroke', new_stroke_path %>

app/views/strokes/new.html.erb
<h1>New stroke</h1>

<%= render 'form' %>

<%= link_to 'Back', strokes_path %>

app/views/strokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theta:</strong>
  <%= @stroke.theta %>
</p>

<p>
  <strong>Type:</strong>
  <%= @stroke.type_id %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @stroke.shape_id %>
</p>

<p>
  <strong>Pos:</strong>
  <%= @stroke.pos %>
</p>

<%= link_to 'Edit', edit_stroke_path(@stroke) %> |
<%= link_to 'Back', strokes_path %>